# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=63)),
                ('slug', models.SlugField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('parts', models.IntegerField()),
                ('level', models.IntegerField()),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel')),
            ],
            options={
                'ordering': ['level', 'parts'],
            },
        ),
    ]
